export * from './Footer/Footer';
export * from './Header/Header';
export * from './Genres/Genres'
export * from './Genre/Genre'
export * from './Movie/Movie';
export * from './Movies/Movies'
export * from './MovieList/MovieList'
export * from './MovieCard/MovieCard'
export * from './MovieDetails/MovieDetail'
export * from './Pagination/Pagination'