export * from './Footer/Footer';
export * from './Header/Header';
export * from './Genres/Genres'
export * from './Movie/Movie';
export * from './MoviesList/MoviesList'
export * from './MovieCard/MovieCard'
export * from './MovieDetail/MovieDetail'
export * from './Pagination/Pagination'
export * from './SearchMovie/SearchMovie'
